### ISSUE TITLE
Graph.Community.SiteUserRequest

### ISSUE THREAD

**Issue by Ofer-Gal** [microsoftgraph/msgraph-sdk-dotnet-contrib#39]
Can you give an example of "EnsureUser"?

I need to add an item with a people field. 
Thanks

**Comment by pschaeflein** [comment]
The test project has most of the requests, including EnsureUser.

https://github.com/microsoftgraph/msgraph-sdk-dotnet-contrib/blob/a3afad8de11bbdc65de31d1e1ba3ee86d95dc08f/test/WebRequestTests.cs#L252

```csharp
var response = await gsc.GraphServiceClient
          .SharePointAPI(mockWebUrl)
          .Web
          .Request()
          .EnsureUserAsync("alexw");
```

Because the data passed to the EnsureUser method is sent in the request body, the method was added after the Request is instantiated. (By convention, methods/properties before the Request() call are added to the url.)
